using ProTecht.Enum;
using ProTecht.Enum;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ProTecht.Quotes
{
    public class QuoteManager : QuoteManagerBase
    {
        //<suite-custom-code-autogenerated>
        public QuoteManager(IQuoteRepository quoteRepository)
            : base(quoteRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}