using ProTecht.People;
using ProTecht.Enum;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ProTecht.Quotes
{
    public class Quote : QuoteBase
    {
        //<suite-custom-code-autogenerated>
        protected Quote()
        {

        }

        public Quote(Guid id, Guid? personId, Vendor vendor, string? amount = null)
            : base(id, personId, vendor, amount)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}