using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ProTecht.People
{
    public class PersonManager : PersonManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PersonManager(IPersonRepository personRepository)
            : base(personRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}