using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ProTecht.People
{
    public class Person : PersonBase
    {
        //<suite-custom-code-autogenerated>
        protected Person()
        {

        }

        public Person(Guid id, Guid personId, string name, string surname, int age, string? contactNumber = null, string? vehicleRegistration = null, string? vehicleType = null)
            : base(id, personId, name, surname, age, contactNumber, vehicleRegistration, vehicleType)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}