using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using ProTecht.Permissions;
using ProTecht.People;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using ProTecht.Shared;

namespace ProTecht.People
{
    public class PeopleAppService : PeopleAppServiceBase, IPeopleAppService
    {
        //<suite-custom-code-autogenerated>
        public PeopleAppService(IPersonRepository personRepository, PersonManager personManager, IDistributedCache<PersonDownloadTokenCacheItem, string> downloadTokenCache)
            : base(personRepository, personManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}